### PR TITLE
added GW proxy resolver plugin

### PR DESCRIPTION
**Pull request by dsavchenko**

### CODE REVIEW

**Review by volodymyrss — CHANGES_REQUESTED** [review]
could you please add a test? There are plenty of examples in there. It will also clarify how the name is resolved through different plugins. You may (and maybe even need to?) also modify that the plugin resolution login, but if it is necessary, we have to think about it carefully.

**Comment by dsavchenko** [comment]
I have added tests and fixed some bugs. 
The only thing that I am not fully happy with is the values for view.t1, view.t2. It is 'duration' before t0 and 2 x duration afterwards, which was probably inspired by GRBs. For GW we don't need the long interval after t0 but are rather interested in the previous time. 
Should we split the logic to construct the interval differently if the name is resolved by gw plugin? Or should we construct it in the universal way to be used in 'multi-messenger'?

**Comment by volodymyrss** [comment]
I am wondering if you need this to even run tests and demonstrations. Maybe you mentioned it. If so, we can set it to the next patch release.

**Comment by dsavchenko** [comment]
> I am wondering if you need this to even run tests and demonstrations. Maybe you mentioned it. If so, we can set it to the next patch release.

Not sure I understand what you mean

**Comment by volodymyrss** [comment]
> > I am wondering if you need this to even run tests and demonstrations. Maybe you mentioned it. If so, we can set it to the next patch release.
> 
> Not sure I understand what you mean

how do you use the resolver? did you deploy it yourself?

**Comment by dsavchenko** [comment]
On my development installation, I deploy it as separate pod. And I hard-code it instead of https://github.com/oda-hub/frontend-astrooda/blob/7be22227e70ba2d9fa69f29f3a48342e34eea047/astrooda.nameresolver.inc#L4 in frontend (not the best way of course)
On APC installation, the internal resolver just doesn't work, because "cdcihn" is not resolved (anyway, no need for grb/gw for now).

**Comment by volodymyrss** [comment]
> I have added tests and fixed some bugs. The only thing that I am not fully happy with is the values for view.t1, view.t2. It is 'duration' before t0 and 2 x duration afterwards, which was probably inspired by GRBs. For GW we don't need the long interval after t0 but are rather interested in the previous time. Should we split the logic to construct the interval differently if the name is resolved by gw plugin? Or should we construct it in the universal way to be used in 'multi-messenger'?

Thanks!

Yeah, it make sense that different instruments favor different viewing range but indeed we need to construct universal interval, since it's in the multi-messenger, source-based panel.  

Maybe plugins could also return some `min_extra_viewing_range_before`, `min_extra_viewing_range_after`, and if provided, combine with the GRB-inspired default range (by taking max of both minimally required ranges).

**Comment by dsavchenko** [comment]
I think it could be merged, it works in principle. I created a separate issue about minimal time range https://github.com/oda-hub/oda-resolver/issues/7

**Review by volodymyrss — APPROVED** [review]

**Pull request merged**
